language: rust

matrix:
  include:
    - os: linux
    - os: osx

before_deploy:
  - mv "$(which pihex)" .
  - zip pihex_"$(uname | awk '{ print tolower($0) }')".zip pihex

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: XyW+e/mr5Vot+pBpexgAYh1wswGc4x+WEc3EsdNhMMf2F6lpMpOjbMMsGA1xJlJZjXoTkry4jcHCXC2F4cZ+3fhYbwlE6ivr4zvwBVGrr9DdVQIsgCPlagavDXMQUJy+xhWdF2bRUAL6I5okdD8sDdhKhLre0/jGtn/yI2txQaQVSBL65h3oM3opXBwcL/AogPzrudCypKRv5G6xlyZsnY8lCOHnldP9J9NuAwdzBe2VwmKnZfzh9wTEuTYQH/a49vnqeLJGmfMscAgbC0crjOHycdba5gMlCutib0Icf1WIML8hxZUd8jYXbhc9UIuKTI1uxIKUjig1SFXGjVTJo8VZBKbKGWQ4ZNw50Me4nLpXjkW3tTX3lxQ6x658au4TQzmXfnTujUtFJm5WhhbmzyXsJP8Sz6bpOrK/tpHAtVv8Hl1P8bfRCcc5LoQN9J7SP/TjxmJwj6EZ7S8jadQgteuhLIbkxcj97fS3QrcyV1qiO/s6M4StMNUBnspcJNLTi0h0SpwHh345U835TSekrhgTuxnocvy3No5IjlIembGvY6f03Ulv90Jmufmzprvn74LqVy4UORTSaqJh9Kmpeav/bo1spEozAnwf+4Ha+PTJi9sPI1L8AAkK4zNZaYvH0A0ZNY7gCKCOZB2QgsiRWxB49cNnlZh5zfy3wv283S4=
  file: ./*.zip
  file_glob: true
  on:
    repo: itchyny/pihex-rs
    tags: true
    all_branches: false
