[package]
name = "pihex"
version = "0.1.1"
authors = ["itchyny <itchyny@hatena.ne.jp>"]
description = "Arbitrary place hexadecimal digits viewer of pi written in Rust"
repository = "https://github.com/itchyny/pihex-rs"
readme = "README.md"
license = "MIT"
keywords = ["pi", "math"]
categories = ["algorithms"]

[dependencies]
clap = "2.21"

[[bin]]
name = "pihex"
doc = false
