[package]
name = "pihex"
version = "0.1.0"
authors = ["itchyny <itchyny@hatena.ne.jp>"]
description = "Arbitrary place hexadecimal digits viewer of pi written in Rust"
readme = "README.md"
license = "MIT"
keywords = ["pi", "math"]
categories = ["algorithms"]

[dependencies]
clap = "2.21"
